name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          # Assuming your project is a Node.js project
          npm ci
          npm run build

      - name: Debug Print Build Folder
        run: |
          ls -R build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}
